name: Test workflow

on:
  push:
    branches: [ master ]

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.0.0
        with:
          minikube version: 'v1.9.2'
          kubernetes version: 'v1.18.2'
      - name: Interact with the cluster
        run: kubectl get nodes
      - name: Deploy the app
        uses: okteto/apply@master
        with:
          manifest: manifest.yml
      - name: Show Pods
        run: kubectl get pods --show-labels
